/**
 * Generate pyproject.toml for Kedro project
 */

import type { ProjectMetadata } from './staticFilesGenerator';

/**
 * Generate pyproject.toml content
 */
export function generatePyproject(metadata: ProjectMetadata): string {
  const { projectName, pythonPackage, description } = metadata;

  return `[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "${pythonPackage}"
version = "0.1.0"
description = "${description || 'A Kedro project generated by Kedro Pipeline Builder'}"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
    "kedro>=0.19.0",
    "kedro-datasets[pandas]>=2.0.0",
    "pandas>=2.0.0",
    "numpy>=1.23.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "kedro-viz>=6.0.0",
    "ipython>=8.0.0",
]

[tool.kedro]
package_name = "${pythonPackage}"
project_name = "${projectName}"
kedro_init_version = "0.19.0"
tools = ""
example_pipeline = "False"
source_dir = "src"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.coverage.run]
branch = true
source = ["${pythonPackage}"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
]
`;
}
